SpineEventEngine/SpineEventEngine.github.io

js/gfm-add-toc.user.js
Original code is:
http://tomancaklab.github.io/gfm-add-toc.user.js
Modified after StackOverflow advice:
http://stackoverflow.com/questions/31844206/how-can-i-automatically-gene
rate-tables-of-contents-in-a-github-wiki
=> Add Greasemonkey script

_config.yml
This PR adds `githuburl` item into `_config.url` similarly to how it's done for gRPC site, which supports https (and is also based on GitHub Pages).
=> Enable https

Gemfile.lock
... reported by GitHub.
See https://nvd.nist.gov/vuln/detail/CVE-2017-18258 for details.
=> Bump Nokogiri -> 1.8.2 to fix security vulnerability

_config.yml, _layouts/base.html, alexander/index.html, jee18/index.html
In this changeset we make sure that GA analytic data is submitted **before** a user is taken away from the spine.io/jee18 and spine.io/alexander pages to the site homepage. 
Also the GA tag is now a site-level variable to reuse across places.
=> Ensure that Google Analytics pageview event is submitted for landing pages

alexander/index.html, jee18/index.html
Previously the GA script was duplicated on each of the JEE18 landing pages. Also, even with the submission of the pageview before redirecting users to the homepage, the pageviews sometimes were not counted.
Now we count landing on the main page using URL parameters instead of submitting a separate pageview from each of the landing pages. Also a duplication of GA script is eliminated. 
Simpler is better.
=> Simplify gathering stats for JEE18 landing pages

docs/guides/naming-conventions.md
This PR improves language on naming command files.
=> Fix language in Naming Conventions guide

docs/guides/naming-conventions.md, docs/prior-art.md
This PR:
1. adds text on naming entities and repositories;
2. improves layout of the Prior Art document (which is not included into navigation for now).
=> Improve conventions guide

_layouts/docs.html, _sass/base/_common.scss, _sass/modules/_buttons.scss, _sass/modules/_footer.scss, _sass/modules/_nav.scss, _sass/pages/_faq.scss, blog/index.html, js/common.js
This PR brings `Go to Top` button for the docs pages that appears when the user scrolls down 1500px from the top of the document. To review it better go to the Docs > Guides > Naming Conventions.
Also were fixed:
1. FAQ-section margins;
2. hover states for the collapsible toggles in the mobile header and footer;
3. simplified functions in the `common.js` file.
=> Implement `Go to Top` button. And fix small issues.

_includes/doc-side-concepts-nav.html
This is the fix for #132 
In Concepts navigation: 
- Changed "Messages" header name into "Messaging",
- Swapped"Messaging" and "Entities" sections.
=> Modifying Concepts section navigation and header's name to fix #132

_includes/doc-side-guides-nav.html, about/index.html, docs/guides/validation-user-guide.md, docs/quickstart/java.md
In Java Quick Start guide (quickstart/java.md):
1. Fixed the code alignment in requestFactory.command().create().
2. Added a note on vBuilder and fixed vBuilder() vs newBuilder() naming.
3. Added Validation User Guide to source control and created a link to this guide from Java Quick Start Guide and spine.io/about page, Built-in Validation feature description.
=> Fixes for issue #141:

faq/index.html
Changes addressing issue #117: 
In FAQ > in index.html file added an entry describing our future plans.
Note: Roadmap placement can be discussed. We can add a Roadmap page in the top-right navigation bar on spine.io website.
=> Changes addressing issue #117 "Create Roadmap page" 

_includes/doc-side-guides-nav.html, docs/guides/defining-aggregate.md, docs/guides/naming-conventions.md
Changes addressing issue #82: 
1.) Created defining-aggregate.md page with Coming soon content;
2.) Added a page to Guides navigation section;
3.) In naming-conventions.md added a link to Defining Aggregates guide from “Entity States” section of the “Naming Conventions” document;
4). In naming-conventions.md added a link to Defining Rejections user guide (was a TODO item in this document).
=> Changes addressing issue #82: "Defining Aggregate guide"

docs/concepts/acknowledgement.md, docs/concepts/diagrams/spine-architecture-diagram.svg
This PR adds a stub page for Acknowledgement — in order to provide a navigation destination for a corresponding arrow at the Architecture diagram.
Also, an order of SVG elements was updated to make the "Event Store" element properly clickable.
=> Add a stub page for Acknowledgement

docs/concepts/diagrams/spine-architecture-diagram.svg
In this changeset the "Results" and "Subscribe" arrow captions made green — a markup issue has been fixed.
Also, the positioning of the captions was updated to make them closer to the corresponding arrows.
=> Adjust "Results" and "Subscribe" captions on the Architecture diagram

docs/concepts/diagrams/spine-architecture-diagram.svg, js/architecture-diagram.js
Prior to this changeset the architecture diagram had `foreignObject` tags with an embedded HTML code to display captions. Such an SVG feature isn't widely supported by SVG editor tools.
This PR migrates to using SVG `text` tags instead of `foreignObject` + HTML.
=> Use SVG `text` tags instead of embedded HTML

docs/concepts/diagrams/spine-architecture-diagram.svg, js/architecture-diagram.js
This PR slightly modifies the SVG diagram and the related JS file by removing the unused attributes and reformatting the code. Also, the opacity of the text in "faded" mode has been changed to look better.
=> Architecture diagram cleanup

docs/examples/index.md, docs/reference/index.html
This is a PR to improve the content of `Reference` and `Example` index pages. 
In both files the following adjustments were made to introduction phrases: 
- Revision and editing.
- Formatting style changed to paragraph style to conform to other Docs pages formatting style.
In addition to it, 
-  API Reference page name fixed to `Language-specific API Reference`.
-  in Examples section changed the `TBD` to `Coming soon` style.  
TODO: web designer's help is needed for API index page css style adjustments.
=> Text and formatting fixes of Reference and Examples pages

docs/concepts/aggregate.md
Fixed links within the framework of issue #175. 
- `https://spine.io/java/aggregate.md` is replaced with `https://spine.io/docs/tutorials/basic/java.html`
- `https://spine.io/biz-model/aggregate-states.md` is replaced with `https://developers.google.com/protocol-buffers/docs/overview`
=> Fixing broken links on Aggregate concept page for issue #175

docs/guides/naming-conventions.md
In `naming-conventions.md` file added a note on using `java_outer_classname` in proto files to address issue #102.
=> Adding a note to Naming Conventions Guide to address issue #102

docs/concepts/command-handler.md
Made the following changes to `command-handler.md` file:
- Added a note Aggregate being an example of classes used in Command Handler example; 
- Fixed example formatting issue.
=> Changes to Command Handler concept

_includes/doc-side-concepts-nav.html, docs/concepts/integration-event.md
This changeset updates the "Integration Event" page with some content.
Also, an order of the items in the "Concepts" navigation bar was changed to put "Integration Event" lower than the more important concepts such as "Command Bus".
This PR addresses #154.
=> Add `IntegrationEvent` concept

_includes/doc-side-concepts-nav.html, _includes/doc-side-quickstart-nav.html, _includes/doc-side-tutorial-nav.html, js/common.js
This PR closes #123.
In this PR I have added a new function that hides a `toc` functionality if a page has less than 3 sub-headers.
As part of the PR, I have also fixed a `doc-side` navigation and used a `Jekyll Liquid` to make sure that the current state matches the selected item in the `doc-side` navigation.
=> Hide a `toc` functionality if a page has less than 3 sub-headers

docs/concepts/event-subsriber.md
In this PR I have used angle brackets for the generic parameters in the example code on the `Event Subscriber` page.
=> Use angle brackets for the generic parameters in the code example

about/index.html, docs/guides/defining-aggregate.md, docs/guides/validation-user-guide.md, docs/reference/cpp/index.md, docs/reference/javascript/index.md, docs/reference/swift/index.md
Also remove redundant dividers (i.e. `<hr>`) on the "Coming soon..." pages.
=> Fix the link to the validation guide.

_layouts/base.html, _layouts/docs.html, docs/concepts/index.md
This PR fixes #210.
This PR fixes a bug with appearing a `body` scroll on Windows.
It has happened because the custom js scripts were loaded before the `common.js`.
In this PR I have changed the order of the custom js scripts including and place them after the `common.js`.
=> Fix `body` scroll jumping

_posts/2019-08-21-Spine-Event-Engine-1-0-is-Out.md
The URL is updated according to Using URLs in Markdown recommendations.
=> Update link to Key concepts internal page in the blog post.

_includes/doc-nav.html, _includes/doc-side-nav.html, _includes/nav.html, _layouts/base.html, _layouts/docs.html, _posts/2018-05-21-blog-is-now-live.md, _posts/2018-05-22-migrating-to-java-8.md, _posts/2019-08-21-spine-event-engine-1-0-is-out.md, _sass/base/_colors.scss, _sass/base/_common.scss, _sass/base/_config.scss, _sass/base/_markdown.scss, _sass/base/_text.scss, _sass/modules/_doc-nav.scss, _sass/pages/_docs.scss, docs/examples/index.md, docs/index.html, docs/reference/index.html, js/common.js, js/os-licenses.js, privacy/index.html
This PR closes #217, #205.
In this PR I have recreated the document page layout and make it according to the design:
Also, I have fixed several bugs:
- TOC had a duplicated menu item at the top;
- `doc-side-nav-mobile-toggle` was visible at 768px but the column hadn't had hidden yet;
- the `body-class` in the `base.html` had the wrong definition.
As part of the PR, I have also made sticky TOC functionality universal to use it for the `side-doc-nav`. And also, I have cleaned up the `common.js` file.
=> Update document page layout

docs/quickstart/java.md
This PR fixes the outdated code in the `Quick Start/Java` guide.
It also updates the actual `quick-start` sub-project version to the latest `master`.
=> Update the `Quick Start/Java` guide

_layouts/base.html
Remove the `onload` event, because it causes an error if ` common.js` hasn't loaded yet.
The function will be called inside the script.
=> Remove duplicated `onload="PR.prettyPrint()"`

Gemfile.lock
The  `nokogiri` module version was updated in this PR.  This is the Git Hub suggestion to avoid this module vulnerability.
=> Fix `nokogiri` module vulnerability issue

js/common.js
This PR brings a custom hash generation function that removes all punctuation symbols from the hash.
It fixes a bug when the generated hash has some punctuation symbol and it doesn't match with the title id. For example `improved-areas:` in the hash and `improved-areas` in the title.
=> Fix `Toc` hash generation

_data/navigation/README.md, _data/navigation/doc_side_nav.yml, _includes/doc-side-nav.html
This PR brings simplified attribute names for side navigation.
Also, the `REAMDE.md` file was updated.
The new structure for the three-level navigation list:
```
doc_side_nav:
- page: Messaging
children:
- page: Architecture Overview
url: /docs/architecture-overview.html
- page: Event
children:
- page: New page on the 3rd level
url: /docs/3rd-level-file.html
```
The `id` and `href` that are needed to create a collapsible navigation item now will be generated automatically based on a page name in the `_includes/doc-side-nav.html` file.
Result:
=> Simplify the document side navigation

docs/motivation.md, docs/prior-art.md, docs/tutorials/basic/cpp.md, docs/tutorials/basic/java.md, docs/tutorials/basic/javascript.md, docs/tutorials/basic/swift.md, docs/tutorials/index.md, js/common.js
This PR closes #234 
In this PR the obsolete `.md` file attributes were removed.
The `header` was fixed for the situation when the user followed the link to a specific section of the page.
=> Cleanup `.md` file attributes

docs/examples/index.md
This PR:
* Removes C++ section of examples.
* Adds links to JS-related examples from the ToDo List project.
=> Add JavaScript example links

_sass/base/_full-screen.scss, _sass/base/_markdown.scss, _sass/modules/_feature-cards.scss, _sass/modules/_nav.scss, _sass/pages/_about.scss, docs/introduction/diagrams/spine-architecture-diagram-full-screen.html, index.html
This PR brings fixes for small UI issues:
- `C++` was replaced with the `Dart` on the home page in the `Step 2` text.
- The header layout for the architecture diagram in full-screen was fixed.
- Heading styles were defined again to don't depend on `h1` style changes.
=> Fix UI issues

_sass/base/_common.scss, _sass/base/_markdown.scss, _sass/pages/_faq.scss, faq/index.html
This PR brings updated styles for the `FAQ` page in accordance with the new style of the main text.
Added faq item dividers and gray background for the open item.
=> Update `FAQ` page styles in accordance with the new style of the main text

Gemfile.lock, _data/navigation/doc_side_nav.yml, docs/introduction/naming-conventions.md, docs/introduction/rules.md
This PR:
* Adds the Rules page into the Introduction section.
* Removes the note block from the Naming Conventions page. This note should be [given](#265) in the document which explains creating a proto file.
* Bumps some dependencies.
=> Rules page

_data/navigation/doc_side_nav.yml, _includes/feature-section.html, _includes/footer.html, _posts/2020-03-02-integrating-with-a-third-party.md, about/index.html, docs/introduction/concepts.md, docs/introduction/development.md
Since recently, more generated documentation is published to `spine.io`. In this PR we add links to the new docs and update links to the docs which have changed their directory structure.
Also, the link to "API Reference" on the home page now leads to the general "Docs" page, as we've got no special page for API reference overview and I'm not convinced that we need one.
=> Update references to generated doc

_layouts/licenses.html, _sass/base/_markdown.scss, _sass/base/_mixins.scss, _sass/pages/_about.scss, _sass/pages/_licenses.scss, os-licenses/index.html
This PR closes #274 and closes #273 issues.
In this PR the ordered and unordered list styles were moved to the new mixin to avoid code duplication. The `markdown` page type was removed from the OS Licenses page to fix the layout.
=> Fix the OS Licenses page

_layouts/post.html, _posts/2018-05-21-blog-is-now-live.md, _posts/2018-05-22-migrating-to-java-8.md, _posts/2019-08-21-spine-event-engine-1-0-is-out.md, _posts/2020-03-02-integrating-with-a-third-party.md, _sass/base/_colors.scss, _sass/modules/_hero.scss, _sass/modules/_nav.scss, _sass/pages/_about.scss, _sass/pages/_blog.scss, _sass/pages/_landing.scss, about/index.html, privacy/index.html
This PR partially addresses #240.
This PR brings small UI changes:
- the sticky menu color was changed to blue;
- the blog post content was aligned exactly in the center;
- fixed `Our Clients` section layout on the `About` page.
=> Update sticky menu color and fix `Blog` page layout

_layouts/base.html
This PR brings the `2018 – <current-year>` period to the copyright section in the footer.
=> Add the year period to the copyright

_sass/base/_diagram.scss, _sass/base/_markdown.scss, _sass/base/_text.scss, css/style.scss, docs/introduction/architecture.md, docs/introduction/diagrams/spine-architecture-diagram-full-screen.html
This PR:
1. Adds top margin for the architecture diagram.
2. Adds emphasis for the “some of them” text.
3. Adds explanation that those “some” components are not shaded on the diagram by default.
=> Add top margin for arch. diagram

_data/navigation/doc_side_nav.yml, _includes/footer.html, _includes/nav.html
This PR fixes broken links in mobile navigation and footer.
Fixed links:
- `Quick Start`;
- `Guides`;
- `Tutorials` link has been removed.
Also, the `Overview` page will be active on UI, if it is the current page.
=> Fix broken navigation and footer links

_data/navigation/doc_side_nav.yml, _includes/footer.html, _includes/nav.html, _sass/base/_markdown.scss, docs/index.md, docs/reference/index.md
In this PR I have moved all the `API Reference` links from the side navigation to the separate page `/docs/reference/index.md`.
=> Add `API Reference` page as `index` page

docs/index.md, docs/introduction/naming-conventions.md
This PR fixes the link to the Guides page.
And also removes the block with the link to the `Defining Aggregate Guide` page.
=> Fix the link to the Guides

_sass/modules/_nav-search.scss, js/common.js
This PR prepares variables to make it easy to define a screen size when the search input should be opened on mobile.
This is useful when we start adding new pages to the main navigation.
=> Prepare screen size variables to easy switch to mobile search

_includes/nav.html, docs/index.md
This PR brings the `Resources` link to mobile navigation and to the document overview page.
=> Add `resources` link to the mobile navigation

Gemfile.lock
This PR brings `html-proofer` dependency to the `Gemfile.lock`.
=> Add `html-proofer` dependency to the `Gemfile.lock`

.github/workflows/links-check.yml, README.md
This PR brings changes to the links check task flow. 
The GitHub rejects links checks from the `html-proofer` tool. The issue is described  [here](https://github.com/gjtorikian/html-proofer/issues/226). I added ignore rule for external GitHub links to avoid wrong error messages.
=> Add ignore rule for external GitHub links to the links checker command.

_posts/2018-05-21-blog-is-now-live.md, _posts/2018-05-22-migrating-to-java-8.md, _posts/2019-08-21-spine-event-engine-1-0-is-out.md, _posts/2020-02-08-learning-at-ddd-europe-2020.md, _posts/2020-03-02-new-guide-on-integrating-with-third-party.md
This PR closes #337 issue. 
The post category `categories: blog` config changes post path in `_site` folder and changes URL for the post. 
This configuration should be added in every new post, if we want to have the same files structure.
=> Add post category and change posts URL by this config

docs/guides/start-new-project.md
In this PR I have fixed links to internal resources introduced in #338.
Whenever referencing a link, one should use links from the rendered header, but not the dynamic side-nav menu. Even though the dynamic link works, it never passes the build.
=> Fix internal references

AUTHORING.md, Gemfile, Gemfile.lock, _config.yml, _posts/2018-05-21-blog-is-now-live.md, contribute/index.html
This PR brings a [Jekyll Email Protect](https://github.com/vwochnik/jekyll-email-protect) plugin to protect our emails from spam bots.
```
<a href="mailto:{{ 'example@example.com' | encode_email }}">{{ 'example@example.com' | html_encode_email }}</a>
```
Or through a variable:
```
<a href="mailto:{{ site.data.support.email | encode_email }}">{{ site.data.support.email | html_encode_email }}</a>
```
```
[{{ Contact us }}](mailto:{{ site.data.support.email | encode_email }})
```
=> Add email protect

docs/examples/index.md
This PR improves the Examples page by:
* adding the Airport example;
* adding links to the guides corresponding to the examples.
=> Add Airport example, and article links

docs/quick-start/index.md
This PR fixes leackage of `embed-code` Jekyll subcommand to the content of the Quick Start page.
=> Fix embedding command leackage

docs/introduction/diagrams/spine-architecture-diagram.svg
This PR removes the `<?xml?>` line from the SVG file to fix it displaying on UI.
Please see #359 for details.
=> Fix the architecture diagram SVG

docs/guides/integration.md, docs/quick-start/index.md
Some articles published on the site are using tocify.js which generates the table of contents from the `h2`, `h3` etc tag contents. However, as it turns out, the script hardly works with self-closing custom tags such as 
```
<embed-code file="..." start="..." end="..."/>
```
In this case, the generated TOC has many repeated items, probably due to a failure to determine which header item contains which.
This changeset replaces all the self-closing `embed-code` tags to an open-close version:
```
<embed-code file="..." start="..." end="..."></embed-code>
```
Another minor change is the changed name of the `test` source folder along with its description.
=> Fix TOC generation

AUTHORING.md, _includes/doc-next-prev-nav.html, _layouts/docs.html, _sass/base/_common.scss, _sass/modules/_doc-next-prev-nav.scss, _sass/pages/_docs.scss, css/style.scss, docs/index.md, docs/quick-start/index.md
This PR closes #356. 
This PR provides an automatic generation of the “Prev”/“Next” buttons for all document pages.
The logic is based on the navigation `doc_side_nav.yml`.
Also added the ability to customize these buttons if we need to hide them or add our own name or URL.
The instruction added to the `AUTHORING.md` file.
=> Link documentation pages using “Prev”/“Next” buttons

docs/introduction/index.md
This PR fixes the grammar issue of using “another” with a singular countable noun (instead of “other”).
Also the text of the Contributor's guide was updated along with new `config`.
=> Fix another grammar

faq/index.html
This PR simplifies the FAQ item on the framework name.
=> Remove redundant links in FAQ item

.idea/misc.xml, docs/guides/gradle.md, docs/quick-start/index.md
This PR updates the text of the Quick Start guide to reflect the changes made in the Hello World example application, which was migrated to the 1.5.29 version of the Spine Bootstrap plugin.
IDEA Gradle plugin configuration is now done automatically and no manual work is required from the framework user.
=> Update Quick Start guide to use latest Bootstrap plugin

docs/guides/gradle.md, docs/quick-start/index.md
In this PR we update the Gradle user guide to reflect the recent changes to the Bootstrap plugin. Users don't have to add dependencies to `spine-web`, `spine-firebase-web`, and `spine-datastore` libraries manually anymore — now there's API for that.
=> Update Gradle guide

docs/resources/sites.md
Add a link to "Learning DDD" to the Sites section of DDD Resources.
=> Update list of DDD resources

_layouts/base.html, index.html
This PR replaces the `Spine / Spine Event Engine` title with the `Spine Event Engine` for the home page.
=> Simplify title for the index page

_includes/getting-help/service-section.html
This PR fixes the situation when checkboxes are still checked but the button is disabled when hitting the `back` button.
Also, open the privacy pages in the new browser tab to avoid misunderstanding how to back to the page.
=> Fix checkboxes when hitting the `back` button

_layouts/release-notes.html, _sass/base/_common.scss, _sass/pages/_release-notes.scss
This PR closes #396.
This PR fixes the flex column width that was broken by the `pre` element on screens between `992px` and `1258px`.
=> Fix the `Release Notes` layout that was broken by the `pre` element

_data/payment_config.yml, js/pricing.js
Order URL was updated according 2checkout requirements for ConvertPlus plan.  
The checkout url was updated, the `CUSTOMERID` parameter was changed to `customer-ext-ref` and `signature` was added. On the server side signature generator was implemented. https://github.com/SpineEventEngine/site-backend/pull/8
=> Update 2checkout order link

_data/support.yml
This PR brings a new email `sales@spine.io` instead of the `sales@teamdev.com`.
=> Update email address

_includes/getting-help/service-section.html, _sass/pages/_getting-help.scss, getting-help/index.html
This PR removes subtitles on the `Getting Help` page.
Also, column widths were fixed on mobile devices and the CSS variables were refactored.
=> Remove subtitles on the `Getting Help` page

_sass/modules/_nav-search.scss
This PR hides the default WebKit `X` icon from the search input.
The default icon doesn't suit us in the style. It is dark and not visible on the blue background. If we try to add a custom icon it has some functionality problems.
=> Hide the default Webkit `X` icon from the search input

.gitattributes, _script/check-samples, _script/embed-code, _script/jekyll-build, _script/jekyll-serve, _script/proof-links
This PR improves our helper scripts setup allowing users with different Bash setups to use them without being forced to create custom configuration files.
It is usually a preferred way to rely on the user's `env` configuration over hard-coding the `/bin/bash` shebang. Also, users may not use `bash` as their default shell, then they will not have the bash profile file available. The last change is the usage of the POSIX-compatible [dot command](https://www.shell-tips.com/bash/source-dot-command/) over the Bash-specific `source` command to make the script a bit more friendly to other shells.
=> Make scripts friendlier to custom setups

docs/guides/validation.md, docs/introduction/naming-conventions.md
In this PR I have ported our naming conventions for `repeated` and `map` types from the repository Wiki [page](https://github.com/SpineEventEngine/SpineEventEngine.github.io/wiki/Protobuf-Code-Style#naming-repeated-and-map-fields) to the published docs.
There's a known code highlight [issue](https://github.com/rouge-ruby/rouge/issues/1640) with Proto examples that have the `map` type.
=> Add Proto `repeated` and `map` naming convention

_sass/base/_code-highlight.scss
This PR overrides the default Bootstrap property to make code snippets with the horizontal scroll in mobile Safari.
=> Make code snippets with the horizontal scroll on mobile

_sass/pages/_landing.scss, index.html
This PR brings updates to the collapsible functionality on the home page.
The button label changes to the `Hide code` if the item is opened.
=> Change `Show code` on `Hide code` if the item is opened

docs/quick-start/index.md
I came across a minor typo in [Getting started with Spine in Java](https://spine.io/docs/quick-start/) documentation. Here is the fix.
Before:
<code>
The first field of the type holds <b>and</b> ID of this entity
</code>
After:
<code>
The first field of the type holds <b>the</b> ID of this entity
</code>
=> Fix typo in quick start doc

about/index.html
This PR fixes the failed link to [Travis](https://app.travis-ci.com/github/SpineEventEngine).
=> Fix the link to Travis

_includes/footer.html, _includes/nav.html
This PR closes #437.
This PR removes the “Blog” item from the top navigation and footer.
=> Remove Blog item from all navigations

_sass/pages/_landing.scss, index.html
This PR closes #439.
This PR makes the “Show code” buttons more visible and aligns them with the landing image.
https://user-images.githubusercontent.com/22611365/149762495-8f3eeaba-8743-44d9-b82b-95ddc7f94a6d.mov
=> Make “Show code” actions more visible

.gitmodules, README.md, _config.yml, _data/navigation/NAVIGATION.md, _data/navigation/doc_side_nav.yml
This PR re-imports the [documentation](https://github.com/SpineEventEngine/documentation.git) repository as a collection inside the `_docs` directory. 
It is needed to avoid `docs/docs` URL. Also, navigation URLs have been cleaned up.
=> Update submodule with documentation

_config.yml, _layouts/base.html
Google Tag Manager script was added in this PR. It will replace outdated `analytics.js` script. 
On first stage I will setup new GA4 Property and connect it with UA Property. Then will remove the outdated analytics script.
=> Add Google Tag Manager script.

_config.yml, _layouts/base.html
The Google Universal Analytics script was removed in this PR, because we will use Google Tag Manager for properties management.
=> Remove Google Universal Analytics script

Gemfile.lock
This PR updates dependencies to fix the vulnerability message.
=> Bump Nokogiri to 1.13.4

_data/navigation/release_notes_nav.yml, release-notes/2022/v1.8.2.md
This changeset adds the notes for the most recent public release of Spine Event Engine.
=> Add the release notes for Spine 1.8.2

js/oss-licenses.js, oss-licenses/index.html
In scope of this changeset, a few things were improved in relation to displaying the third-party dependencies along with their licenses:
1. New `dependencies.md` file is now loaded from each repository instead of `license-report.md` as the latter is being renamed due to [config#498](https://github.com/SpineEventEngine/config/issues/498). For those repositories, in which such a renaming is not done yet, `license-report.md` is still loaded as a fallback.
2. In reports, the repeating sections telling about dual-licensing and crediting the Gradle plugin for dependency reporting are moved from per-artifact blocks to the top of [this page](https://spine.io/oss-licenses/). Also, we don't display the generation time for each artifact, as it may be fetched from its publication date anyway.
3. …
=> Improve dependency reports

.github/workflows/check-code-embedding.yml, .github/workflows/proof-links.yml, sitemap.xml
Previously, our `sitemap.xml` only contained relative URLs, which prevented Google Search from using this sitemap.
In this PR, absolute URLs are now used. See [Google's best practices](https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap#general-guidelines).
=> List all `sitemap.xml` entries with an absolute URL

robots.txt
Currently, a sitemap syntax in our `robots.txt` is incorrect, as it refers to the `sitemap.xml` file via a relative URL.
According to [Google's recommendations](https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt), the URL must be absolute. This PR does just that.
=> Use an absolute URL for sitemap in `robots.txt`

robots.txt
Previously, there were several thousand `404` responses detected by Google Search Console review process, the majority of which were related to the generated documentation for Spine Dart client.
Attempts to address the problem, or at least, locate its roots failed. Seems like some previously crawled pages are still in Google Search cache, but now (as of `1.9.0` release) they are missing.
Therefore, within this PR, the whole `/dart/` subtree is excluded from crawling altogether. Hopefully, it will enforce the cache cleanup.
In some future, we may re-enable the crawling for this part of the site. Most likely, it will make sense to do together with 2.0.0 release.
=> Exclude `/dart/` from crawling

sh
Previously, our sh helper script was printing the name of Spine's examples organisation as `Spine-examples`. This isn't exactly right.
This changeset updates the spelling to use a small `s`.
=> Use proper capitalization when referring to `spine-examples` in our helper sh script
