- css/spine.css
- index.html
It is going to be a separate page.
> Remove How to Contribute block

- _sass/base/_common.scss
- blog/index.html
In this PR were added paddings for Blog Page sidebar and added bottom margin for blog sidebar heading.
> Sidebar navigation fix

- _layouts/base.html
This PR makes obtaining the font done over https to prevent security warning.
> Get font securely

- index.html
This PR fix plurals of the code names.
> Fix plurals in landing text

- about/index.html
This PR adjusts the feature list at the About page.
> About page fixes

- _sass/modules/_nav.scss
In this PR was fixed sticky navigation position when page is scrolled up.
> Fix sticky navigation position

- alexander/index.html
- jee18/index.html
In order to improve visitor tracking, we are creating a https://spine.io/jee18 page.
Another page created in this PR is https://spine.io/alexander placeholder to track those who used the QR code from the Alexander's business card.
This PR creates empty pages which immediately redirect a user to the homepage, but send the analytics report beforehand.
> Add a placeholder for JEEConf'18 landing pages.

- Gemfile.lock
- about/index.html
> Update links to CloudRepo

- _includes/footer.html
- _layouts/landing.html
- _layouts/post.html
- _sass/base/_common.scss
- _sass/base/_config.scss
- _sass/base/_markdown.scss
- _sass/base/_override.scss
- _sass/modules/_buttons.scss
- _sass/modules/_doc-nav.scss
- _sass/modules/_footer.scss
- _sass/modules/_hero.scss
- _sass/modules/_nav.scss
- _sass/pages/_blog.scss
- _sass/pages/_docs.scss
- _sass/pages/_faq.scss
- _sass/pages/_landing.scss
- blog/index.html
- faq/index.html
- img/icon-arrow-back.svg
- img/icon-caret-right.svg
- index.html
This PR brings updated styles for the Blog and FAQ pages.
Updated layout for the mobile devices.
> Fix blog and FAQ pages

- _sass/base/_common.scss
- _sass/base/_footer-at-bottom.scss
- _sass/base/_override.scss
- _sass/modules/_hero.scss
- _sass/pages/_docs.scss
- _sass/pages/_landing.scss
- index.html
This PR brings:
- updated shadow styles for the cards in the docs page;
- fixed `pre` tag horizontal scroll and wrapping;
- landing feature cards have the same height size;
- footer at the bottom made with Flex.
> Fix home page

- _sass/base/_reset.scss
- _sass/base/_text.scss
This PR brings new styles for blockquotes.
> Add style for quotes #88

- _sass/base/_colors.scss
- _sass/base/_override.scss
- _sass/modules/_feature-cards.scss
- _sass/pages/_about.scss
- about/index.html
- docs/guides/naming-conventions.md
- index.html
This PR brings:
- updated feature section — now feature cards have their height and the same distance between cards;
- updated icons from fontawesome.com site;
- added style for the note block.
> Update feature section and add style for the note text

- _sass/pages/_docs.scss
- docs/index.html
- docs/reference/index.html
- index.html
This PR adds a client-side Java API reference link, and arranges the links in language-specific boxes.
> Add client lib link

- _sass/modules/_cookies.scss
This PR brings updated sizes for the cookie notification “Agree” button.
Also, `translate3D` was changed on `translate` to remove blurred pixel in the text.
> Fix cookie notification button

- js/common.js
This PR brings the fixed `toc` scroll behavior at the bottom of the page for docs pages.
> Fix TOC scroll

- _layouts/base.html
This PR brings fixed Open Graph Image for the social networks.
> Fix the Open Graph Image

- about/index.html
- index.html
Multiple text edits based on previous discussions.
> Multiple text edits

- _includes/doc-side-quickstart-nav.html
- docs/quickstart/index.md
Based on  README #8 PR.
Formatting applied, writing style and grammar revised and adjusted.
> Adding the Quick Start section contents on Spine.io website 

- docs/concepts/command-handler.md
- docs/concepts/event-subsriber.md
Fixing issues #135 and #136:  
1. In command-handler.md:
- removed reference to Java section
- paraphrased the concept
2. In event-subsriber.md:
Added a reference to Projection concept as an example.
> Fixing issues #135 and #136

- index.html
In spine.io index.html:
- Replaced newBuilder() with vBuilder().
- Replaced getBuilder() with builder().
> Addressing issue #140 in Spine.io homepage

- _includes/doc-side-guides-nav.html
- about/index.html
- docs/concepts/rejection.md
- docs/guides/validation-user-guide.md
- docs/quickstart/java.md
The following fix was made to address #134 in rejection.md file: 
`CreditCardValidationDecllined` was changed to `CreditCardValidationDeclined`.
> Changing rejection.md file to fix issue #134

- _includes/doc-side-guides-nav.html
- docs/guides/creating-rejection-messages.md
Addressing issue #130  
A draft version of Guide on creating Rejection messages is created: 
* Created a new entry in "Guides" section 
* Issue #130 proposed content revised, edited and formatted.
TODO: 
1.) Think about the proper guide placement. 
2.) Add a link to the guide from Rejection concept and other places where appropriate.
> Draft version of Rejection Messages Guide to address issue #130

- _includes/doc-side-concepts-nav.html
- docs/concepts/event-reactor.md
- Added Event Reactor concept contents to version control
- Modified doc-side-concepts-nav.html file to reflect new Concepts section structure
> Fixing issue #137

- faq/index.html
Multiple text edits in FAQ section index.html file: Adjusting grammar and writing style.
> Revising and editing FAQ section of the website

- _includes/doc-side-guides-nav.html
- docs/concepts/rejection.md
- docs/guides/creating-rejection-messages.md
In rejection.md file added a reference to Creating Rejection Messages Guide to address issue #150 and improve the documentation user experience.
> Adding a reference to Creating Rejection Messages Guide to address issue #150.

- _includes/doc-side-concepts-nav.html
- _includes/doc-side-quickstart-nav.html
- _includes/doc-side-tutorial-nav.html
- _includes/nav.html
- js/common.js
This PR closes #155 issue.
In this PR the `Concepts` page was added to the mobile hamburger menu.
Also, side navigation on the `Concepts` page was fixed.
> Add `Concepts` page to the mobile  hamburger  menu

- _includes/hero.html
In hero.html changed the product headline to "Apply Domain-Driven Design smarter and faster, with less code."
> Changing Spine headline

- faq/index.html
Changes addressing issue #164:
- Changed the formatting style for the list to make it a bulleted one,
- Removed redundant <li> tag,
- Replaced ; with . for one element of the list.
> Fixing FAQ page issues to address issue #164

- docs/guides/naming-conventions.md
This is a PR addressing improvements in naming-conventions.md file: 
- Writing style, grammar fixes,  and structure improvements (converted some text entries to notes).
> Improvements in naming-conventions.md file

- _includes/footer.html
This PR aims to add a link to `Documentation` > `Concepts` section in site footer in `footer.html` file.
> Adding Concepts link to spine.io footer section 

- _includes/doc-side-concepts-nav.html
Concepts TOC fixed: redundant Messages section removed.
> Concepts TOC fixed: redundant Messages section removed.

- docs/concepts/aggregate-mirror.md
In `aggregate-mirror.md` fixed backquotes style.
> Fixing backquotes style in Aggregate Mirror concept

- .gitmodules
This PR replaces `examples-java` submodule with submodules referring to newly created dedicated example repositories.
> Split examples

- docs/index.html
This PR fixes titles in the Documentation home.
> Fix title and headline

- index.html
This PR updates home page code snippets to user newer API which was recently introduced in `core-java`.
> Update code snippets to new API

- google1c5034bde35ad090.html
In this PR I have added google site verification file to have the ability to use google console.
> Add google verification file

- docs/examples/index.md
This PR:
1. Fixes links to example repositories.
2. Adds a link to ToDo List example.
> Fix example links

- _sass/base/_common.scss
- _sass/base/_markdown.scss
- _sass/base/_mixins.scss
- _sass/pages/_docs.scss
- css/style.scss
- docs/guides/naming-conventions.md
- js/common.js
In this PR I have updated scroll behavior to the anchor point on the `docs` and `faq` pages.
I have separated functions that are used only for the FAQ page. And also, I have adjusted the offset value for the `docs` pages.
All mixins were extracted to the `base/_mixins.scss` file.
> Fix scroll behavior

- _sass/pages/_blog.scss
In this PR I have adjusted paddings on the `post` page to add more space between footer and content.
> Adjust `post` page paddings

- js/common.js
This PR brings a fixed `go-to-top` button. The problem was that the button wasn't shown on the page.
> Fix `Go-to-top` button

- about/index.html
This PR:
* Adds description of architectural patterns on which Spine is based.
* Adds links to storage repositories.
* Adds the link to Dart client library.
* Updates example submodules.
> Update About with architectural patterns and links to repositories

- about/index.html
- index.html
This PR brings the updated feature section to the `Home` and `About` pages.
The functions were combined from these two pages.
> Update the feature section

- docs/introduction/development.md
This PR updates code snippets in the Development Process page.
> Update projection code snippets

- _includes/snackbar.html
- _layouts/base.html
- _layouts/docs.html
- _sass/modules/_snackbar.scss
- css/style.scss
- js/common.js
- js/scroll-to-anchor.js
- js/snackbar.js
This PR brings new functionality that allows copying the URL to the clipboard by clicking on the anchor link near the heading. After clicking the snackbar notification will be shown at the left bottom corner.
> Copy the URL to clipboard by clicking on the anchor heading

- _sass/base/_common.scss
- _sass/modules/_nav.scss
- _sass/pages/_blog.scss
This PR brings small style fixes for the arrow icon alignment.
> Update icon alignment styles

- _sass/pages/_about.scss
- about/index.html
This PR updates the About page in the following ways:
* Features section was removed. We have features on the home page. Let's DRO.
* Added the Principles section. It is the first step for removing the Motivation page from the Introduction.
* Consolidated tools and online systems into one section.
* Moved libraries into a separate section updating the text. We need to have a separate section for Clients, so Libraries got light blue background color.
* Clients come in a separate section with updated title.
* Added the call to action to the bottom.
> Improve the About page

- _sass/base/_colors.scss
- _sass/base/_text.scss
- docs/guides/validation-user-guide.md
In this PR we add the Spine [validation user guide](https://spine.io/docs/guides/validation-user-guide.html).
> Validation doc

- _includes/nav.html
- _layouts/post.html
- _sass/base/_common.scss
- _sass/base/_config.scss
- _sass/base/_override.scss
- _sass/modules/_nav.scss
- _sass/pages/_blog.scss
- _sass/pages/_privacy.scss
- _sass/pages/_search-result.scss
- css/style.scss
- docs/introduction/architecture.md
- docs/introduction/development.md
- privacy/index.html
- search/index.html
This PR brings Google Search input to the main site header. And a separate page with the `Search Results`, which was customized for our site.
> Add Google Search to the site

- _sass/modules/_nav.scss
This PR brings small fixes to align navigation icons.
> Align navigation icons

- faq/index.html
This PR closes #286.
This PR adds the FAQ item `Do you support Maven?`.
> Add a new FAQ item

- _includes/footer.html
- _layouts/base.html
- _sass/modules/_footer.scss
- _sass/modules/_nav-search.scss
- js/copyright.js
This PR brings small UI fixes:
- The inline `copyrightYear` function has been moved to the external JS file.
- The Algolia bug with a jump in letters was fixed.
- The brand color is now used to highlight an item in focus in the Algolia dropdown.
> Fix UI issues

- _includes/doc-side-nav.html
- _sass/modules/_doc-side-nav.scss
This PR closes #305.
In this PR I created unique IDs for the side navigation items to fix the Bootstrap bug. 
And also I removed the obsolete title.
> Fix document side navigation

- js/copyright.js
This PR brings the updated copyright year.
2015 — is the year when repositories became visible.
> Update copyright year

- .github/workflows/links-check.yml
GitHub action flow rule was fixed in this PR
> Update GitHub action flow rule

- _data/navigation/doc_side_nav.yml
- _includes/nav.html
- docs/index.md
- docs/resources/blogs.md
- docs/resources/books.html
- docs/resources/communities.md
- docs/resources/index.html
- docs/resources/libraries.md
- docs/resources/people.html
- docs/resources/sites.md
This PR renames the` Resources` section to the `DDD Resources`.
> Rename `Resources` to `DDD Resources`

- _layouts/release-notes.html
- _sass/base/_code-highlight.scss
- _sass/base/_colors.scss
- _sass/base/_common.scss
- _sass/base/_config.scss
- _sass/base/_text.scss
- _sass/modules/_buttons.scss
- _sass/modules/_color-selector.scss
- _sass/modules/_cookies.scss
- _sass/modules/_doc-side-nav.scss
- _sass/modules/_feature-cards.scss
- _sass/modules/_hero.scss
- _sass/modules/_nav-search.scss
- _sass/modules/_nav.scss
- _sass/modules/_snackbar.scss
- _sass/pages/_about.scss
- _sass/pages/_blog.scss
- _sass/pages/_licenses.scss
- _sass/pages/_release-notes.scss
- js/common.js
This PR brings subscription information to the Release Notes.
This information block contains a text to `Subscribe to @SpineEngine on Twitter`. And it will be visible at all “release notes” pages.
Also, common variables were cleaned up and added to the `config.scss` file.
> Add subscription info to the Release Notes

- _sass/base/_code-highlight.scss
- _sass/base/_config.scss
- _sass/base/_markdown.scss
- _sass/modules/_hero.scss
- _sass/modules/_nav.scss
- _sass/pages/_landing.scss
- _sass/pages/_licenses.scss
- _sass/pages/_release-notes.scss
> Add font variables

- docs/quick-start/index.md
This PR adds the text on handling the command by the `Console` Process Manager.
> Quick Start Guide: add text on handling the command 

- docs/guides/validation.md
This PR closes #355, closes #353, closes #354.
This PR fixes small spelling mistakes.
> Fix typo in documentation

- getting-help/service-section.html
- js/pricing.js
This PR shows the tooltip only on the disabled button and hides it on the enabled button.
> Show the tooltip only on the disabled button

- .idea/misc.xml
- Gemfile.lock
- about/index.html
This PR updates the links at the About page to point to corresponding documentation pages under the Client Libraries section (see #378).
> Client lib links

- privacy/development-support-agreement.md
This PR updates `Development Support Agreement` title.
> Update Development Support Agreement title

- _includes/getting-help/service-section.html
This PR brings small fixes to the text on the Getting Help page.
> Fix text on the Getting Help page

- _includes/getting-help/recaptcha-note.html
- _sass/modules/_cookies.scss
- _sass/modules/_recaptcha-note.scss
- _sass/pages/_getting-help.scss
- css/style.scss
- getting-help/index.html
Custom reCAPTCHA note was removed in this PR. We are using default badge view instead.
> Change reCAPTCHA note

- _config.yml
- _data/navigation/release_notes_nav.yml
- _includes/getting-help/service-section.html
- _sass/base/_markdown.scss
- _sass/base/_mixins.scss
- release-notes/2020/v1.6.0.md
This PR adds a new version `1.6.0` to the Release Notes.
> Add version `1.6.0` to the Release Notes

- release-notes/2020/v1.6.0.md
This PR fixes the publication date.
> Fix the publication date

- _includes/footer.html
- _sass/modules/_footer.scss
- privacy/terms-of-use.md
This PR brings the `Terms of Use` page. 
The page link has been added to the footer.
> Add `Terms of Use` page

- privacy/terms-of-use.md
This PR updates trademark text in the “Terms of Use” document.
> Update Terms of Use

- _config.yml
- _data/navigation/release_notes_nav.yml
- release-notes/2020/v1.7.0.md
This PR adds a new release notes page for the `v1.7.0`.
> Add release notes for the `v1.7.0`

- release-notes/2020/v1.7.0.md
This PR updates the publication date.
> Update Release Notes date

- _sass/pages/_landing.scss
- docs/introduction/concepts.md
- index.html
This PR makes code blocks collapsible on the homepage.
> Make code blocks collapsible on the homepage

- _data/navigation/release_notes_nav.yml
- release-notes/2021/v1.7.5.md
This PR adds a new release notes page for `v1.7.5`.
> Add release notes for `v1.7.5`

- _data/navigation/release_notes_nav.yml
- release-notes/2021/v1.8.0.md
This PR adds a new release notes page for `v1.8.0`.
> Add release notes  for `v1.8.0`

- faq/index.html
This PR brings the updated submodule with documentation.
> Update submodule with documentation

- _config.yml
This PR updates the documentation submodule and adjusts links in `_config.yml` to match those in `_docs/config.yml`.
> Update documentation submodule

- sh
This changeset exposes an sh script, serving as a helper tool for Spine Event Engine newcomers.
> Add an `sh` script
